#!/usr/bin/perl
while (<STDIN>) {
   $Line1 = $_;
   $v = "?}";
   if (/G}/)  {
     $Line2 = <STDIN>;  # grab comment line
     $Line3 = <STDIN>;  # grab \cline 

     print $Line1;
     print $Line3;
     print "%       |S--F||----{\\eG}----||{\\eG}{\\sG}|   |----{\\teG}----||--{\\eG}{\\sG}{\\teG}--|   |---{\\eG}{\\nG}---||---{\\eG}{\\xG}---|\n";

     for (1..6) {
       $LineA = <STDIN>;
       $LineB = <STDIN>;
       $LineA =~ s/\s*//g;     # this trashes all white space
       $LineB =~ s/\s*//g;     # this trashes all white space
       ($LineLeftA, $LineRightA) = split(/\s*%/, $LineA);
       ($LineLeftB, $LineRightB) = split(/\s*&/, $LineB);
       ($z, $a, $b, $c, $d, $e, $f, $g, $h, $i, $j, $k, $l) = split(/{/, $LineLeftA);
       ($Z, $A, $B, $C, $D, $E, $F, $G, $H, $I, $J, $K, $L) = split(/{/, $LineLeftB);

       if ($_ == 4) {
         printf "     \\xa{%s{%s{%s{%s{%s{%s{%s{%s\\xb{%s{%s{%s{%s{%s{%s{%s{%s\\xc{%s{%s{%s{%s{%s{%s{%s{%s    &&%c  %s\n",
              $a, $b, $c, $d, $A, $B, $C, $D, 
              $e, $f, $g, $h, $E, $F, $G, $H, 
              $i, $j, $k, $l, $I, $J, $K, $L, 0x25, $LineRightA;
       }
       else {
         printf "     \\xa{%s{%s{%s{%s{%s{%s{%s{%s\\xb{%s{%s{%s{%s{%s{%s{%s{%s\\xc{%s{%s{%s{%s{%s{%s{%s{%s     &%c  %s\n",
              $a, $b, $c, $d, $A, $B, $C, $D, 
              $e, $f, $g, $h, $E, $F, $G, $H, 
              $i, $j, $k, $l, $I, $J, $K, $L, 0x25, $LineRightA;
       }
     }
   }
   else {
     print;
   }

}

