#!/usr/bin/perl
while (<STDIN>) {
   $Line1 = $_;
   if (/G}/)  {
     $Line2 = <STDIN>;
     $Line3 = <STDIN>;
     $Line4 = <STDIN>;

     print $Line1;
     $Line1 =~ s/^\s*//;     # this trashes leading white space
     ($a, $b, $c, $d, $e, $f, $g, $h) = split(/\s*&/, $Line1);
     print "%       |  | {\\eG} |{\\eG}{\\sG} | {\\teG} |  |{\\eG}{\\sG}{\\teG}|{\\eG}{\\nG} |{\\eG}{\\xG}|\n";
     print "     \\xa{}{}{} {} {}{}\\xb{0}{0}{0}{0}{0}{0}     % ",  $a, "\n";
     print "     \\xc{}{}{} {} {}{}\\xd{0}{0}{0}{0}{0}{0} &   % ",  $a, "\n";
     print "     \\xa{}{}{} {} {}{}\\xb{0}{0}{0}{0}{0}{0}     % ",  $b, "\n";
     print "     \\xc{}{}{} {} {}{}\\xd{0}{0}{0}{0}{0}{0} &   % ",  $b, "\n";
     print "     \\xa{}{}{} {} {}{}\\xb{0}{0}{0}{0}{0}{0}     % ",  $c, "\n";
     print "     \\xc{}{}{} {} {}{}\\xd{0}{0}{0}{0}{0}{0} &   % ",  $c, "\n";
     print "     \\xa{}{}{} {} {}{}\\xb{0}{0}{0}{0}{0}{0}     % ",  $d, "\n";
     print "     \\xc{}{}{} {} {}{}\\xd{0}{0}{0}{0}{0}{0} &&  % ",  $d, "\n";
     print "     \\xa{}{}{} {} {}{}\\xb{0}{0}{0}{0}{0}{0}     % ",  $f, "\n";
     print "     \\xc{}{}{} {} {}{}\\xd{0}{0}{0}{0}{0}{0} &   % ",  $f, "\n";
     print "     \\xa{}{}{} {} {}{}\\xb{0}{0}{0}{0}{0}{0}     % ",  $g, "\n";
     print "     \\xc{}{}{} {} {}{}\\xd{0}{0}{0}{0}{0}{0} &   % ",  $g, "\n";
     print $Line2;
     print "\\\\ ", $Line4;
   }
   else {
     print;
   }

}

