#!/usr/bin/perl
while (<STDIN>) {
   $Line1 = $_;
   $Line2 = <STDIN>;
   $Line3 = <STDIN>;
   $Line4 = <STDIN>;


   print $Line1;
   ($a, $b, $c, $d, $e, $f, $g, $h) = split(/&/, $Line1);
   print "%        S  F  S  C  F     S  C  F  S  C  F\n";
   print "     \\xx{ }{ }{ }{ }{ }\\xy{ }{ }{ }{ }{ }{ } &   % ",  $a, "\n";
   print "     \\xx{ }{ }{ }{ }{ }\\xy{ }{ }{ }{ }{ }{ } &   %  ", $b, "\n";
   print "     \\xx{ }{ }{ }{ }{ }\\xy{ }{ }{ }{ }{ }{ } &   %  ", $c, "\n";
   print "     \\xx{ }{ }{ }{ }{ }\\xy{ }{ }{ }{ }{ }{ } &&  %  ", $d, "\n";
   print "     \\xx{ }{ }{ }{ }{ }\\xy{ }{ }{ }{ }{ }{ } &   %  ", $f, "\n";
   print "     \\xx{ }{ }{ }{ }{ }\\xy{ }{ }{ }{ }{ }{ } &   %  ", $g, "\n";
   print $Line2;
   print "\\\\ ", $Line4;

}

