#!/usr/bin/perl
while (<STDIN>) {
   $Line1 = $_;

   if (/G}/)  {
     $Line2 = <STDIN>;  # grab comment line
     $Line3 = <STDIN>;  # grab \cline 

     print $Line1;
     print $Line2;
     print $Line3;

     for (1..6) {
       $LineA = <STDIN>;
       $LineB = <STDIN>;
       $LineA =~ s/\s*//g;       # this trashes all white space
       $LineB =~ s/\s*//g;       # this trashes all white space
       ($LineLeftA, $LineRightA) = split(/\s*%/, $LineA);
       ($LineLeftB, $LineRightB) = split(/\s*&/, $LineB);
       $LineLeftA =~ s/}//g;         # this trashes all }
       $LineLeftB =~ s/}//g;         # this trashes all }
       $LineLeftA =~ s/\\xb//;       # this trashes all 
       $LineLeftB =~ s/\\xd//;       # this trashes all
       $LineRightB =~ s/%/% /;       # this trashes all

       ($z, $a, $b, $c, $d, $e, $f, $g, $h, $i, $j, $k, $l) = split(/{/, $LineLeftA);
       ($Z, $A, $B, $C, $D, $E, $F, $G, $H, $I, $J, $K, $L) = split(/{/, $LineLeftB);

       print "  \\begin{tabular}{\@{}c\@{}*{11}{|\@{}c\@{}}}\n";
       print "     \\myhead\n";
       printf "    %s & %s & %s & %s & %s & %s & \\,%s\\, & %s & %s & %s & %s & %s \\\\ \\hline %c %s\n", $a, $b, $c, $d, $e, $f, $g, $h, $i, $j, $k, $l, 0x25, $LineRightA;
       printf "    %s & %s & %s & %s & %s & %s & \\,%s\\, & %s & %s & %s & %s & %s           %s\n", $A, $B, $C, $D, $E, $F, $G, $H, $I, $J, $K, $L, $LineRightB;
       print "  \\end{tabular} ";

       if ($_ == 4) {
         print " && \n";
       }
       elsif ($_ == 6) {
         print "\n";
       }
       else {
         print " & \n";
       }

     }
   }
   else {
     print;
   }

}

